import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd(); const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8');
test('final background renderer is still-image-only and uses approved eight-photo rotation', () => { const renderer = read('src/components/layout/environment-background.tsx'); assert.match(renderer, /environment-still-image/); assert.match(renderer, /millisecondsUntilNextBackgroundSlot/); assert.match(renderer, /nextEnvironmentBackgrounds/); assert.match(renderer, /data-background-rotation="8-photo-approved-v9"/); assert.doesNotMatch(renderer, /youtube\.com\/iframe_api/); assert.doesNotMatch(renderer, /<video/); });
test('adaptive pool contains eight mood-based local-time slots', () => { const environment = read('src/lib/environment.ts'); for (const minute of [0,300,390,540,750,960,1110,1230]) assert.match(environment, new RegExp(`slotStartMinute: ${minute}`)); for (const id of ['approved-deep-night-dubai-terrace','approved-predawn-blue-dubai','approved-sunrise-mountain-lake','approved-morning-mountain-lake','approved-midday-nature-terrace','approved-afternoon-dubai','approved-golden-hour-dubai','approved-night-dubai-city']) assert.match(environment, new RegExp(id)); });
test('final CSS still retires video surfaces', () => { const css = read('src/app/premium-physical-ui-final.css'); assert.match(css, /environment-still-image/); assert.match(css, /environment-background video/); assert.match(css, /environment-background iframe/); assert.match(css, /display: none !important/); });
test('all eight approved daily backgrounds are packaged locally', () => { const dir = path.join(root, 'public/backgrounds/adaptive'); assert.equal(fs.existsSync(dir), true); const files = fs.readdirSync(dir).filter((name) => /^\d{2}-.+\.png$/.test(name)).sort(); assert.equal(files.length, 8); for (const file of files) assert.ok(fs.statSync(path.join(dir, file)).size > 250_000); });
